version: 2.1
jobs:
  build_and_test:
    working_directory: ~/sdk
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Accept licenses and Build
          command: yes | sdkmanager --licenses || true
      - run:
          name: Build
          command: ./gradlew check build assembleAndroidTest
  publish_to_maven:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Publish
          command: ./gradlew publish
  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run:
          name: Publish Release on GitHub
          command: ./gradlew createGitHubRelease
workflows:
  build_and_test:
    jobs:
      - build_and_test
# TODO: Uncomment before merge
#  deploy:
#    when:
#      and:
#        - equal: [ master, << pipeline.git.branch >> ]
#    jobs:
#      - publish_to_maven:
#          requires:
#            -  build_and_test
#      - publish_github_release:
#          requires:
#            - publish_to_maven
