version: 2.1
jobs:
  build_and_test:
    working_directory: ~/sdk
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Build
          command: ./gradlew check build assembleAndroidTest
  publish_to_maven:
    docker:
      - image: circleci/android:api-30
    steps:
      - run:
          name: Hello Maven
          command: echo "Hello Maven!"
          #TODO replace Hello Maven with Publish task
#      - run:
#          name: Publish to Maven
#          command: ./gradlew publish
  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run:
          name: Hello GitHub
          command: echo "Hello GitHub!"
          #TODO replace Hello GitHub with Publish task
#      - run:
#          name: Publish Release on GitHub
#          command: ./gradlew createGitHubRelease
workflows:
  build_test_and_deploy:
    jobs:
      - build_and_test
      - publish_to_maven:
          filters:
            branches:
              only:
                - "story/7460_automate-releases"
          requires:
            - build_and_test
      - publish_github_release:
          filters:
            branches:
              only:
                - "story/7460_automate-releases"
          requires:
            - publish_to_maven
